spring:
  application:
    name: LMS
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb;encrypt=true;trustServerCertificate=true;
    username: sa
    password: admin@123

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE